frontend/teaedi/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth.views import login, logout
from django.contrib.auth.decorators import login_required
from .core import views, apis
urlpatterns = [
    # URLs for the django admin site
    url(r'^admin', admin.site.urls),

    # URLs for the TEAEDI app
    url(r'^index/$', login_required(views.Index.as_view()), name='index'),
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, {'next_page': '/index/'}, name='logout'),
    url(r'^purchase_order/$',
        login_required(views.PurchaseOrderList.as_view()),
        name='po-list'),
    url(r'^purchase_order/(?P<pk>[a-zA-Z0-9]+)/$',
        login_required(views.PurchaseOrderDetail.as_view()),
        name='po-detail'),
    url(r'^purchase_order/(?P<pk>[a-zA-Z0-9]+)/reprocess/$',
        login_required(views.PurchaseOrderReprocess.as_view()),
        name='po-reprocess'),

    url(r'^shipping_invoice/pending/$',
        login_required(views.ShippingInvoicePending.as_view()),
        name='shipping-invoice-pending'),
    url(r'^shipping_invoice/all/$',
        login_required(views.ShippingInvoiceAll.as_view()),
        name='shipping-invoice-all'),
    url(r'^shipping_invoice/(?P<pk>[a-zA-Z0-9]+)/$',
        login_required(views.ShippingInvoiceDetail.as_view()),
        name='shipping-invoice-detail'),
    url(r'^shipping_invoice/(?P<pk>[a-zA-Z0-9]+)/refresh/$',
        login_required(views.ShippingInvoiceRefresh.as_view()),
        name='shipping-invoice-refresh'),

    url(r'watcher/$',
        login_required(views.WatcherList.as_view()),
        name='watcher-list'),
    url(r'watcher/add/$',
        login_required(views.WatcherCreate.as_view()),
        name='watcher-add'),
    url(r'watcher/(?P<pk>[0-9]+)/$',
        login_required(views.WatcherUpdate.as_view()),
        name='watcher-update'),

    url(r'new-po-list/$',
        login_required(views.NewPOList.as_view()),
        name='new-po-list'),
    url(r'all-po-list/$',
        login_required(views.AllPOList.as_view()),
        name='all-po-list'),
    url(r'pending-si-list/$',
        login_required(views.PendingSIList.as_view()),
        name='pending-si-list'),
    url(r'all-si-list/$',
        login_required(views.AllSIList.as_view()),
        name='all-si-list'),

    # URLs for the TEAEDI REST API
    url(r'^api/purchase_order/$', apis.CRUDPurchaseOrder.as_view()),
    url(r'^api/process_acknowledgment/$', apis.ProcessAcknowledgment.as_view()),
    url(r'^api/shipping_invoice/$', apis.ShippingInvoiceList.as_view()),
    url(r'^api/shipping_invoice/(?P<pk>[0-9]+)/processed/$',
        apis.ShippingInvoiceMarkProcessed.as_view()),

    url(r'^.*', login_required(views.Index.as_view())),
]

frontend/teaedi/core/models.py
from __future__ import unicode_literals
from django.db import models


class PurchaseOrder(models.Model):
    ORDER_STATUSES = (
        ('O', 'Open'),
        ('P', 'Processed'),
        ('E', 'Processing Error'),
        ('C', 'Cancelled'),
        ('M', 'Modified'),
    )

    order_id = models.CharField(max_length=30, primary_key=True)
    order_status = models.CharField(
        max_length=2, choices=ORDER_STATUSES, default='O')
    batch_id = models.CharField(max_length=30)
    order_date = models.DateField()
    ship_date = models.DateField()
    customer_po = models.CharField(max_length=30)
    contract = models.CharField(max_length=30)
    isd_name = models.CharField(max_length=100)
    isd_code = models.CharField(max_length=30)
    address_line1 = models.TextField(max_length=100)
    address_line2 = models.TextField(max_length=100, null=True)
    city = models.CharField(max_length=30)
    state = models.CharField(max_length=2)
    zip = models.CharField(max_length=10)
    contact_name = models.CharField(max_length=30)
    contact_phone = models.CharField(max_length=30, null=True)
    contact_fax = models.CharField(max_length=30, null=True)
    contact_email = models.CharField(max_length=100, null=True)
    owed_by_isd = models.DecimalField(
        max_digits=20, decimal_places=2, null=True)
    extra = models.DecimalField(max_digits=20, decimal_places=2, null=True)
    is_ICEV = models.BooleanField(default=False)
    processing_error_txt = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.order_id


class PurchaseOrderLine(models.Model):
    QUANTITY_UOM_CHOICES = (
        ('BK', 'Book'),
        ('KT', 'Kit'),
        ('SP', 'Software Product'),
        ('EA', 'EACH')
    )
    PRICE_CODE_CHOICES = (
        ('03', 'Contract'),
        ('04', 'No Charge'),
    )
    purchase_order = models.ForeignKey(
        PurchaseOrder, on_delete=models.CASCADE, related_name='lines')
    sequence = models.CharField(max_length=30)
    quantity = models.IntegerField()
    quantity_uom = models.CharField(
        max_length=2, choices=QUANTITY_UOM_CHOICES)
    unit_price = models.DecimalField(max_digits=20, decimal_places=2)
    unit_price_code = models.CharField(
        max_length=2, choices=PRICE_CODE_CHOICES)
    sub_total = models.DecimalField(max_digits=20, decimal_places=2)
    ship_date = models.DateField(null=True)
    isbn = models.CharField(max_length=30)
    description = models.TextField()
    student_edition = models.CharField(max_length=30)
    student_edition_cost = models.CharField(max_length=30)
    school_district_owes = models.CharField(max_length=30)

    # The below fields are needed for handling PO Changes.
    original_quantity = models.IntegerField(null=True)
    cancelled = models.BooleanField(default=False)
    modified = models.BooleanField(default=False)
    added = models.BooleanField(default=False)

    def __str__(self):
        return '{} {}'.format(self.purchase_order, self.sequence)


class ShippingInvoice(models.Model):
    INVOICE_STATUSES = (
        ('I', 'Imported'),
        ('RP', 'Ready for Processing'),
        ('P', 'Processed'),
        ('A', 'Accepted'),
        ('E', 'Accepted with Error'),
        ('R', 'Rejected'),
    )

    invoice_id = models.CharField(max_length=30, primary_key=True)
    invoice_status = models.CharField(
        max_length=2, choices=INVOICE_STATUSES, default='I')
    invoice_date = models.DateField()
    purchase_order = models.ForeignKey(
        PurchaseOrder, on_delete=models.CASCADE,
        related_name='shipping_invoice'
    )
    carrier_name = models.CharField(max_length=100, default='UPS')
    carrier_code = models.CharField(max_length=30, default='111')
    actual_ship_date = models.DateField()
    boxes = models.IntegerField()
    weight = models.IntegerField()
    shipping_cost = models.DecimalField(max_digits=20, decimal_places=2)
    tracking_number = models.CharField(max_length=100)
    total_amount = models.DecimalField(max_digits=20, decimal_places=2)

    def __str__(self):
        return self.invoice_id

    @property
    def invoice_total(self):
        return self.invoice_amount + self.shipping_cost


class ShippingInvoiceLine(models.Model):
    QUANTITY_UOM_CHOICES = (
        ('BK', 'Book'),
        ('KT', 'Kit'),
        ('SP', 'Software Product'),
    )

    shipping_invoice = models.ForeignKey(
        ShippingInvoice, on_delete=models.CASCADE, related_name='lines')
    sequence = models.CharField(max_length=30)
    quantity = models.IntegerField()
    quantity_uom = models.CharField(
        max_length=2, choices=QUANTITY_UOM_CHOICES)
    unit_price = models.DecimalField(max_digits=20, decimal_places=2)
    total_amount = models.DecimalField(max_digits=20, decimal_places=2)
    actual_ship_date = models.DateField()
    isbn = models.CharField(max_length=30)
    description = models.TextField()
    student_edition = models.CharField(max_length=30)
    student_edition_cost = models.CharField(max_length=30)
    school_district_owes = models.CharField(max_length=30, null=True)

    @property
    def sub_total(self):
        return self.quantity * self.unit_price

    def __str__(self):
        return '{} {}'.format(self.shipping_invoice, self.sequence)


class Watcher(models.Model):
    EVENT_CHOICES = (
        ('PO_NEW', 'New Purchase Order Imported'),
        ('PO_UPD', 'Purchase Order Updated/Cancelled'),
        ('PO_RPT', 'Batch Purchase Order Report'),
        ('SI_PRO', 'Shipping and Invoice Document Processed'),
        ('SI_ACK', 'Shipping and Invoice Document Acknowledged')
    )

    email_id = models.EmailField(unique=True)
    events = models.CharField(max_length=200)

    def get_events_display(self):
        events_display = []
        event_choices_dict = {k: v for k, v in self.EVENT_CHOICES}
        for event in eval(self.events):
            events_display.append(event_choices_dict[event])
        return events_display

frontend/teaedi/core/forms.py
from django import forms
from .models import Watcher
from openpyxl import load_workbook


class WatcherForm(forms.ModelForm):
    email_id = forms.EmailField()
    events = forms.MultipleChoiceField(choices=Watcher.EVENT_CHOICES)

    class Meta:
        model = Watcher
        fields = ['email_id', 'events']


class ShippingInvoiceForm(forms.Form):
    header_file = forms.FileField()
    detail_file = forms.FileField()

    def clean_header_file(self):
        """ Function validates and parses uploaded header file"""
        uploaded_file = self.cleaned_data['header_file']
        if uploaded_file.name[-4:] != 'xlsx' \
                and uploaded_file.name[-3:] != 'xls':
            raise forms.ValidationError("Unsupported file format, Please "
                                        "upload an .xls or .xlsx file.")
        header_wb = load_workbook(
            uploaded_file, read_only = True, data_only=True)
        header_rows = list(header_wb.active.iter_rows())
        if len(header_rows) != 2:
            raise forms.ValidationError(
                "Invalid header file has been uploaded")
        header_data = [cell.value for cell in header_rows[1]]
        if len(header_data) != 16:
            raise forms.ValidationError(
                "Invalid header file has been uploaded")
        return header_data

    def clean_detail_file(self):
        """ Function validates and parses uploaded detail file"""
        uploaded_file = self.cleaned_data['detail_file']
        if uploaded_file.name[-4:] != 'xlsx' \
                and uploaded_file.name[-3:] != 'xls':
            raise forms.ValidationError("Unsupported file format, Please "
                                        "upload an .xls or .xlsx file.")
        detail_wb = load_workbook(
            uploaded_file, read_only = True, data_only=True)
        detail_rows = []
        for row in detail_wb.active.iter_rows(row_offset=1):
            detail_row = [cell.value for cell in row]
            if len(detail_row) != 6:
                raise forms.ValidationError(
                    "Invalid detail file has been uploaded")
            detail_rows.append(detail_row)
        return detail_rows


class MultipleChoiceFieldNoValidation(forms.MultipleChoiceField):
    def validate(self, value):
        pass


class ActionForm(forms.Form):
    action = forms.CharField(max_length=100)
    id_list = MultipleChoiceFieldNoValidation()

frontend/teaedi/templates/core/index.html
{% extends 'core/layout.html' %}
{% load staticfiles %}

{% block title %}TEAEDI Integration - Home{% endblock %}
{% block head_css %}
{% endblock %}
{% block body_content %}
<!-- page content -->
<div class="right_col" role="main">

  <!-- Top Tiles-->
  <div class="row">
    <div class="col-md-12">
      <div class="">
        <div class="x_content">
          <div class="row">
            <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
              <div class="tile-stats">
                <div class="icon"><i class="fa fa-newspaper-o"></i>
                </div>
                <div class="count green">{{counts.new_pos}}</div>

                <h3>New Purchase Orders</h3>
                <p>Purchase orders waiting to be processed
                    <a href="{% url 'new-po-list' %}"
                       class="btn btn-xs btn-primary pull-right">Download List</a>
                </p>
              </div>
            </div>
            <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
              <div class="tile-stats">
                <div class="icon"><i class="fa fa-list-alt"></i>
                </div>
                <div class="count">{{counts.all_pos}}</div>

                <h3>Total Purchase Orders</h3>
                <p>Count of all Purchase Orders
                    <a href="{% url 'all-po-list' %}"
                       class="btn btn-xs btn-primary pull-right">Download List</a>
                </p>
              </div>
            </div>
            <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
              <div class="tile-stats">
                <div class="icon"><i class="fa fa-clock-o"></i>
                </div>
                <div class="count red">{{counts.new_si}}</div>

                <h3>Pending Shipping Invoices</h3>
                <p>Invoices waiting to be processed or acknowledged by TEA
                    <a href="{% url 'pending-si-list' %}"
                       class="btn btn-xs btn-primary pull-right">Download List</a>
                </p>
              </div>
            </div>
            <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
              <div class="tile-stats">
                <div class="icon"><i class="fa fa-globe"></i>
                </div>
                <div class="count">{{counts.all_si}}</div>

                <h3>Total Shipping Invoices</h3>
                <p>Count of all Shipping Invoices
                    <a href="{% url 'all-si-list' %}"
                       class="btn btn-xs btn-primary pull-right">Download List</a>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Top Tiles-->

  <!-- First Row Boxes-->
  <div class="row">
    <div class="col-md-6 col-sm-6 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h3>Purchase Orders <small>Latest Orders from TEA</small></h3>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <div class="table-responsive">
            <table class="table">
            <thead>
              <tr>
                <th>Order Number</th>
                <th>Order Date</th>
                <th>Order Status</th>
                <th>Ship Date</th>
                <th>ISD Name</th>
                <th>Owed By ISD</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
            {% for po in purchase_orders %}
              <tr>
                <td><a  href="{% url 'po-detail' po.pk %}">{{ po.pk }}</a></td>
                <td>{{ po.order_date|date:"m/d/Y"  }}</td>
                <td>
                  {% if po.order_status == 'O' %}
                    <span class="label label-primary">{{ po.get_order_status_display }}</span>
                  {% elif po.order_status == 'P' %}
                    <span class="label label-success">{{ po.get_order_status_display }}</span>
                  {% elif po.order_status == 'C' %}
                    <span class="label label-danger">{{ po.get_order_status_display }}</span>
                  {% elif po.order_status == 'E'%}
                        <span class="label label-danger" data-toggle="tooltip" data-placement="right"
                              title="{{po.processing_error_txt}}">{{po.get_order_status_display}}
                        </span>
                  {% elif po.order_status == 'M' %}
                    <span class="label label-warning">{{ po.get_order_status_display }}</span>
                  {% endif %}
                </td>
                <td>{{ po.ship_date|date:"m/d/Y"  }}</td>
                <td>{{ po.isd_name }}</td>
                <td>${{ po.owed_by_isd }}</td>
                <td>
                  <a href="{% url 'po-detail' po.pk %}" class="btn btn-xs btn-success">View</a>
                </td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h3>Shipping Invoices <small>Latest Shipments sent to TEA</small></h3>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <div class="table-responsive">
            <table class="table">
            <thead>
                <tr>
                  <th>Invoice Number</th>
                  <th>Invoice Date</th>
                  <th>Invoice Status</th>
                  <th>Order Number</th>
                  <th>Actual Ship Date</th>
                  <th>ISD Name</th>
                  <th>Invoice Amount</th>
                  <th>Actions</th>
                </tr>
              </thead>
            <tbody>
                {% for si in shipping_invoices %}
                  <tr>
                    <td><a  href="{% url 'shipping-invoice-detail' si.pk %}">{{ si.pk }}</a></td>
                    <td>{{ si.invoice_date|date:"m/d/Y"  }}</td>
                    <td>
                      {% if si.invoice_status == 'I' %}
                        <span class="label label-default">{{ si.get_invoice_status_display }}</span>
                      {% elif si.invoice_status == 'P' %}
                        <span class="label label-primary">{{ si.get_invoice_status_display }}</span>
                      {% elif si.invoice_status == 'A' %}
                        <span class="label label-success">{{ si.get_invoice_status_display }}</span>
                      {% elif si.invoice_status == 'R' %}
                        <span class="label label-danger">{{ si.get_invoice_status_display }}</span>
                     {% endif %}
                    </td>
                    <td>{{ si.purchase_order.pk }}</td>
                    <td>{{ si.actual_ship_date|date:"m/d/Y"  }}</td>
                    <td>{{ si.purchase_order.isd_name }}</td>
                    <td>${{ si.total_amount }}</td>
                    <td>
                      <a href="{% url 'shipping-invoice-detail' si.pk %}" class="btn btn-xs btn-success">View</a>
                    </td>
                  </tr>
                {% endfor %}
              </tbody>

          </table>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- First Row Boxes-->

  <!-- Second Row Boxes-->
  <div class="row">

    <div class="col-md-6 col-sm-6 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h3>Notification Settings <small>Who Gets Notified and on Which events.</small></h3>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th>Email ID</th>
                  <th>Watched Events</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {% for w in watchers %}
                  <tr>
                    <td>{{ w.email_id }}</td>
                    <td>
                      <ul class="to_do">
                      {% for event in w.get_events_display %}
                        <li>{{event}}</li>
                      {% endfor %}
                      </ul>
                    </td>
                    <td>
                      <a href="{% url 'watcher-update' w.pk %}" class="btn btn-xs btn-success">Edit</a>
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Second Row Boxes-->

</div>
<!-- /page content -->
{% endblock %}

{% block body_js %}
{% endblock %}

frontend/teaedi/templates/core/shippinginvoice_form.html
{% extends 'core/layout.html' %}
{% load staticfiles %}

{% block title %}TEAEDI Integration - Shipping Invoices{% endblock %}

{% block head_css %}

{% endblock %}

{% block body_content %}
<!-- page content -->
<div class="right_col" role="main">

    <div class="clearfix"></div>

    <!-- po table -->
    <div class="row">

      <div class="col-sm-offset-0 col-sm-12 col-md-offset-3 col-md-6 ">
        <div class="x_panel">
          <div class="x_title">
            <h3>Create New Shipping Invoice</h3>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <br />
            <form class="form-horizontal form-label-left {% if form.header_file.errors or form.detail_file.errors %}has-error{% endif %}"
                method="post" enctype="multipart/form-data" >
              {% csrf_token %}
              <div class="form-group">
                <label class="control-label col-md-3" for="id_header_file">TEA Header File <span class="required">*</span>
                </label>
                <div class="col-md-7">
                  <input type="file" id="id_header_file" required="required"
                         name="header_file" class="form-control col-md-7 col-xs-12"
                         aria-describedby="helpBlock1">
                  <span class="help-block" id="helpBlock1">{{form.header_file.errors}}</span>
                </div>

              </div>
              <div class="form-group">
                <label class="control-label col-md-3" for="id_detail_file">TEA Detail File <span class="required">*</span>
                </label>
                <div class="col-md-7">
                  <input type="file" id="id_detail_file" required="required"
                         name="detail_file" class="form-control col-md-7 col-xs-12"
                         aria-describedby="helpBlock2">
                  <span class="help-block" id="helpBlock2">{{form.detail_file.errors}}</span>
                </div>

              </div>
              <div class="ln_solid"></div>
              <div class="form-group">
                <div class="col-md-7 col-md-offset-3">
                  <input type="submit" class="btn btn-success" value="Create Shipping Invoice"/>
                </div>
              </div>
          </form>
          </div>
        </div>



      </div>

    </div>
    <!-- po table -->
</div>
<!-- /page content -->
{% endblock %}

{% block body_js %}

{% endblock %}

frontend/teaedi/templates/core/shippinginvoice_list.html
{% extends 'core/layout.html' %}
{% load staticfiles %}
{% block title %}TEAEDI Integration - Shipping Invoices{% endblock %}
{% block head_css %}
  <link href="{% static "vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" %}" rel="stylesheet">
{% endblock %}
{% block body_content %}
<!-- page content -->
<div class="right_col" role="main">

    <div class="clearfix"></div>

    <!-- po table -->
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h3>Shipping Invoices <small>You can find all your shipping invoices listed here</small>
            </h3>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <form action="" method="post">{% csrf_token %}
            <table id="datatable" class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th><input type="checkbox" id="checkAll"></th>
                  <th>Invoice Number</th>
                  <th>Invoice Date</th>
                  <th>Invoice Status</th>
                  <th>Order Number</th>
                  <th>Actual Ship Date</th>
                  <th>ISD Name</th>
                  <th>ISD Code</th>
                  <th>Invoice Amount</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {% for si in si_list %}
                  <tr>
                    <td>
                        {% if si.invoice_status == 'I' %}
                          <input type="checkbox" name="id_list" value="{{ si.pk }}">
                        {% else %}
                          <input type="checkbox" disabled>
                        {% endif %}
                    </td>
                    <td><a  href="{% url 'shipping-invoice-detail' si.pk %}">{{ si.pk }}</a></td>
                    <td>{{ si.invoice_date|date:"m/d/Y"  }}</td>
                    <td>
                      {% if si.invoice_status == 'I' %}
                        <span class="label label-default">{{ si.get_invoice_status_display }}</span>
                      {% elif si.invoice_status == 'RP' %}
                        <span class="label label-warning">{{ si.get_invoice_status_display }}</span>
                      {% elif si.invoice_status == 'P' %}
                        <span class="label label-primary">{{ si.get_invoice_status_display }}</span>
                      {% elif si.invoice_status == 'A' %}
                        <span class="label label-success">{{ si.get_invoice_status_display }}</span>
                      {% elif si.invoice_status == 'R' %}
                        <span class="label label-danger">{{ si.get_invoice_status_display }}</span>
                     {% endif %}
                    </td>
                    <td>{{ si.purchase_order.pk }}</td>
                    <td>{{ si.actual_ship_date|date:"m/d/Y"  }}</td>
                    <td>{{ si.purchase_order.isd_name }}</td>
                    <td>{{ si.purchase_order.isd_code }}</td>
                    <td>${{ si.total_amount }}</td>
                    <td>
                      <a href="{% url 'shipping-invoice-detail' si.pk %}"
                         class="btn btn-xs btn-success">View</a>
                      {% if si.invoice_status == 'I' %}
                        <a href="{% url 'shipping-invoice-refresh' si.pk %}"
                           class="btn btn-xs btn-danger">Refresh</a>
                      {% endif %}
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
            </form>
          </div>
        </div>
      </div>
    </div>
    <!-- po table -->
</div>
<!-- /page content -->
{% endblock %}

{% block body_js %}
  <script src="{% static "vendors/datatables.net/js/jquery.dataTables.min.js" %}"></script>
  <script src="{% static "vendors/datatables.net-bs/js/dataTables.bootstrap.min.js" %}"></script>
  <script>
    $(document).ready(function() {
      var table = $('#datatable').DataTable ({
        "responsive": true,
        "order": [[ 1, "desc" ]],
        "columnDefs": [
          { "type": "date", targets: [1, 4] },
          { "searchable": false, "targets": [3, 9] },
          { "sortable": false, "targets": [0, 3, 4, 6, 7, 9] }
        ]
      });
      var action_html =
        '<label>Action: '+
        '<select class="form-control" name="action" id="id_action" required>' +
        '<option selected="selected" value>------------</option>' +
        '<option value="process_selected">Process Selected Invoices</option>' +
        '</select> ' +
        '<button type="submit" class="btn btn-default">Go</button>' +
        '</label>';
      $("#datatable_length").after(action_html);
      $('#checkAll').click(function() {
            if ($(this).is(":checked")) {
                table.rows({page: "current"}).every( function () {
                    var d = this.data();
                    if (! $(d[0]).attr('disabled')) {
                        d[0] = $(d[0]).attr('checked', true)[0].outerHTML;
                    }
                    this.data(d).draw();
                });
            } else {
                table.rows({page: "current"}).every( function () {
                    var d = this.data();
                    d[0] = $(d[0]).attr('checked', false)[0].outerHTML;
                    this.data(d).draw();
                });
            }
        });
    });
  </script>
{% endblock %}

frontend/teaedi/templates/core/watcher_form.html
{% extends 'core/layout.html' %}
{% load staticfiles %}
{% block title %}TEAEDI Integration - Watchers{% endblock %}
{% block head_css %}
  <!-- Select2 -->
  <link href="{% static "/vendors/select2/dist/css/select2.min.css" %}" rel="stylesheet">
{% endblock %}

{% block body_content %}
<!-- page content -->
<div class="right_col" role="main">

    <div class="clearfix"></div>

    <!-- po table -->
    <div class="row">

      <div class="col-sm-offset-0 col-sm-12 col-md-offset-3 col-md-6 ">
        <div class="x_panel">
          <div class="x_title">
            {% if form.instance %}
              <h3>Update Notifications for {{ form.instance.email_id }}</h3>
            {% else %}
              <h3>Create New Notifications</h3>
            {% endif %}
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <br />
            <form class="form-horizontal form-label-left {% if form.email_id.errors %}has-error{% endif %}" method="post">
              {% csrf_token %}
              <div class="form-group">
                <label class="control-label col-md-3" for="id_email_id">Email ID <span class="required">*</span>
                </label>
                <div class="col-md-7">
                  <input type="email" id="id_email_id" maxlength="254" name="email_id"
                         value="{{form.instance.email_id}}" required="required" name="name"
                         class="form-control col-md-7 col-xs-12" aria-describedby="helpBlock1">
                  <span class="help-block" id="helpBlock1">{{form.email_id.errors}}</span>
                </div>

              </div>
              <div class="form-group  form-label-left">
                <label class="control-label col-md-3" for="id_events">Subscribed Events <span class="required">*</span>
                </label>
                <div class="col-md-7">
                  <select id="id_events" name="events" required="required"
                          class="form-control col-md-7 col-xs-12 select_events"
                          multiple="multiple">
                    {% for k, v in form.fields.events.choices %}
                       <option value="{{ k }}" {% if k in form.instance.events %} selected{% endif %}>{{ v }}</option>
                    {% endfor %}
                  </select>
                  <span class="help-block" >{{form.events.errors}}</span>
                </div>

              </div>
              <div class="ln_solid"></div>
              <div class="form-group">
                <div class="col-md-7 col-md-offset-3">
                  <input type="submit" class="btn btn-success" value="Save Mapping"/>
                </div>
              </div>
            </form>
          </div>
        </div>



      </div>

    </div>
    <!-- po table -->
</div>
<!-- /page content -->
{% endblock %}

{% block body_js %}
    <!-- Select2 -->
    <script src="{% static "vendors/select2/dist/js/select2.full.min.js" %}"></script>
    <script>
      $(document).ready(function() {
        $(".select_events").select2({
          maximumSelectionLength: 10,
          placeholder: "Select the events you want to subscribe to",
          allowClear: true
        });
      });
    </script>
    <!-- /Select2 -->
{% endblock %}